baseURL = 'https://rusos.net'
languageCode = 'ru-ru'
title = 'Rusos.net'

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Новости"
    pre = "blog"
    url = "/news/"
    weight = 2

  [[menu.main]]
    name = "TG Каналы"
    pre = "blog"
    url = "/tgchannels/"
    weight = 2
