baseURL = 'https://rusos.net'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'Rusos.net - Русскоговорящие в Уругвае'
googleAnalytics = "G-RWR8YM3FLL"

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Главная"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Новости"
    pre = "blog"
    url = "/news/"
    weight = 2

  [[menu.main]]
    name = "События"
    pre = "blog"
    url = "/events/"
    weight = 2

  [[menu.main]]
    name = "Материалы"
    pre = "blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Места"
    pre = "blog"
    url = "/places/"
    weight = 2

  # [[menu.main]]
  #   name = "TG Каналы"
  #   pre = "blog"
  #   url = "/tgchannels/"
  #   weight = 3
  #
  # [[menu.main]]
  #   name = "Полезные ссылки"
  #   pre = "blog"
  #   url = "/links/"
  #   weight = 4

  [[menu.main]]
    name = "FAQ"
    pre = "blog"
    url = "/faqs/"
    weight = 5

  # [[menu.main]]
  #   name = "О проекте"
  #   pre = "blog"
  #   url = "/about/"
  #   weight = 5
