baseURL = 'https://rusos.net'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'Rusos.net - Русскоговорящие в Уругвае'
googleAnalytics = "G-RWR8YM3FLL"

[languages]
  [languages.ru]
    languageName = "Русский"
    languageCode = "ru"

  [languages.lat]
    languageName = "Russkij"
    languageCode = "lat"

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = "Главная"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = 'news'
    name = "Новости"
    pre = "blog"
    url = "/news/"
    weight = 2
    [menu.main.params]
      description = "Вдали от СНГ новостной фон не такой сильный, но тут важные для эмигрантов собирает"

  [[menu.main]]
    identifier = 'events'
    name = "События"
    pre = "blog"
    url = "/events/"
    weight = 2
    [menu.main.params]
      description = "Встречи, вечеринки и другие события, которые можно посетить лично"

  [[menu.main]]
    identifier = 'posts'
    name = "Материалы"
    pre = "blog"
    url = "/posts/"
    weight = 2
    [menu.main.params]
      description = "Авторские статьи по конретной теме. Хорошо раскрытые темы"

  [[menu.main]]
    identifier = 'places'
    name = "Места"
    pre = "blog"
    url = "/places/"
    weight = 2
    [menu.main.params]
      description = "Карта с отметками от сообщества и отзывами"

  [[menu.main]]
    identifier = 'tgchannels'
    name = "TG Каналы"
    pre = "blog"
    url = "/tgchannels/"
    weight = 3
    [menu.main.params]
      extended = true
      description = "Список известных каналов и чатов. Общих и персональных"

  [[menu.main]]
    identifier = 'links'
    name = "Полезные ссылки"
    pre = "blog"
    url = "/links/"
    weight = 4
    [menu.main.params]
      extended = true
      description = "Местные популярные ресурсы. От гос порталов до досок объявлений"

  [[menu.main]]
    identifier = 'faq'
    name = "FAQ"
    pre = "blog"
    url = "/faqs/"
    weight = 5
    [menu.main.params]
      description = "Короткие ответы на часто задаваемые вопросы"

  [[menu.main]]
    identifier = 'about'
    name = "О проекте"
    pre = "blog"
    url = "/about/"
    weight = 5
    [menu.main.params]
      extended = true
      description = "Расскажем как сделан сайт, как добавить контент и подобное"
