baseURL = 'https://rusos.net'
languageCode = 'ru-ru'
title = 'Rusos.net'

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "TG Каналы"
    pre = "blog"
    url = "/tgchannels"
    weight = 2
