baseURL = 'https://rusos.net'
languageCode = 'ru-ru'
title = 'Rusos.net'
googleAnalytics = "G-RWR8YM3FLL"

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Новости"
    pre = "blog"
    url = "/news/"
    weight = 2

  [[menu.main]]
    name = "TG Каналы"
    pre = "blog"
    url = "/tgchannels/"
    weight = 3

  [[menu.main]]
    name = "Полезные ссылки"
    pre = "blog"
    url = "/links/"
    weight = 4

  [[menu.main]]
    name = "О проекте"
    pre = "blog"
    url = "/about/"
    weight = 5
